#!/usr/bin/env python3
"""Generate self-contained skills from one canonical runtime; --check detects drift."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
SKILLS = ('harness-init', 'harness-recall', 'harness-task', 'harness-remember', 'harness-maintain')
LAUNCHER = b'''#!/usr/bin/env python3
# Generated by scripts/build_dist.py. Edit src/harness_runtime instead.
from harness_runtime.cli import main

if __name__ == "__main__":
    raise SystemExit(main())
'''
REFERENCES = {'harness-init': {'host-integration.md': 'docs/host-integration.md'}}


def outputs() -> dict[Path, bytes]:
    source = ROOT / 'src/harness_runtime'
    files = {path.relative_to(source): path.read_bytes() for path in sorted(source.rglob('*'))
             if path.is_file() and '__pycache__' not in path.parts and path.suffix != '.pyc'}
    result = {}
    manifest = json.dumps({'generator': 'scripts/build_dist.py', 'sha256': {str(path): hashlib.sha256(raw).hexdigest() for path, raw in files.items()}}, sort_keys=True, indent=2).encode() + b'\n'
    for skill in SKILLS:
        base = ROOT / 'skills' / skill
        result[base / 'scripts/harness.py'] = LAUNCHER
        result[base / 'scripts/runtime-manifest.json'] = manifest
        for relative, raw in files.items():
            result[base / 'scripts/harness_runtime' / relative] = raw
        for relative, source_path in REFERENCES.get(skill, {}).items():
            raw = (ROOT / source_path).read_text(encoding='utf-8')
            result[base / 'references' / relative] = raw.encode('utf-8')
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = outputs()
    drift = [str(path.relative_to(ROOT)) for path, raw in expected.items() if not path.is_file() or path.read_bytes() != raw]
    extras = []
    for skill in SKILLS:
        base = ROOT / 'skills' / skill
        for generated in (base / 'scripts', base / 'references'):
            if generated.exists():
                extras.extend(path for path in generated.rglob('*')
                              if path.is_file() and path not in expected and '__pycache__' not in path.parts)
    if args.check:
        if drift or extras:
            print(json.dumps({'generated_drift': drift, 'unexpected_generated_files': [str(p.relative_to(ROOT)) for p in extras]}))
            return 1
        print('Generated skill runtimes match canonical source.')
        return 0
    sys.path.insert(0, str(ROOT / 'src'))
    from harness_runtime.integration import replace_file
    for path in extras:
        path.unlink()
    for path, raw in expected.items():
        if not path.is_file() or path.read_bytes() != raw:
            replace_file(path, raw)
    for skill in SKILLS:
        base = ROOT / 'skills' / skill
        for generated in (base / 'scripts', base / 'references'):
            if generated.exists():
                for directory in sorted((path for path in generated.rglob('*') if path.is_dir()),
                                        key=lambda path: len(path.parts), reverse=True):
                    try:
                        directory.rmdir()
                    except OSError:
                        pass
                try:
                    generated.rmdir()
                except OSError:
                    pass
    print(f'Generated {len(SKILLS)} self-contained skills from one runtime source.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
